version: '3'
services:
  database:
    build: ./database
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: reactblog

  backend:
    depends_on:
      - database
    build: ./backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/reactblog?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:8080"
    container_name: myweb-backend

  frontend:
    depends_on:
      - backend
      - database
    build: ./frontend
    volumes:
      - ./frontend/proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    container_name: myweb-frontend

# .env 파일을 docker-compose.yml 파일과 동일한 폴더안에 만들어두면
# 따로 import 없이 ${} 변수참조만 작성하면 된다.